"""LLMProvider interface — structural Protocol for AI language model providers.

All LLM providers (Gemini, Ollama, OpenAI, etc.) must conform to this
interface so the application layer can remain provider-agnostic.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class LLMProvider(Protocol):
    """Contract for LLM-based text generation providers.

    Each provider encapsulates its own API client, authentication,
    model selection, and generation parameters — the application layer
    only sees this unified interface.
    """

    async def generate(
        self,
        system_prompt: str = "",
        user_prompt: str = "",
        **kwargs: object,
    ) -> str:
        """Send a prompt to the LLM and return the generated text.

        Args:
            system_prompt: System-level instructions defining the LLM's role.
            user_prompt:  The user's request / input message.
            **kwargs:     Provider-specific overrides (temperature, max_tokens,
                         model name, etc.).

        Returns:
            The raw text generated by the LLM.

        Raises:
            LLMProviderError: If the provider cannot fulfill the request.
        """
        ...
